steps:
  - command: "yarn install"
    label: ":yarn: Install Dependencies"
  - wait
  - command: "yarn test"
    label: ":jest: Test"
  - command: "yarn lint"
    label: ":eslint: Lint"
  - command: "yarn build"
    label: ":typescript: TSC Build"
  - command: "yarn esbuild-browser"
    label: ":chrome: ESBuild Browser"
  - command: "yarn esbuild-node"
    label: ":node: ESBuild Node"
      