steps:
  - command: "yarn install;yarn test"
    label: ":jest: Test"
  - command: "yarn install;yarn lint"
    label: ":eslint: Lint"
  - command: "yarn install;yarn build"
    label: ":typescript: TSC Build"
  - command: "yarn install;yarn esbuild-browser"
    label: ":chrome: ESBuild Browser"
  - command: "yarn install;yarn esbuild-node"
    label: ":node: ESBuild Node"